export const services = [
  {
    id: "1",
    type: "Venues",
    vendors: [
      {
        id: "1",
        name: "Grand Hall",
        image: "https://source.unsplash.com/800x600/?venue",
        rating: "4.5",
        price: "$500/hr",
      },
      {
        id: "2",
        name: "Royal Palace",
        image: "https://source.unsplash.com/800x600/?palace",
        rating: "4.8",
        price: "$700/hr",
      },
      {
        id: "3",
        name: "City Convention",
        image: "https://source.unsplash.com/800x600/?convention",
        rating: "4.3",
        price: "$600/hr",
      },
      {
        id: "4",
        name: "Garden Plaza",
        image: "https://source.unsplash.com/800x600/?garden",
        rating: "4.7",
        price: "$550/hr",
      },
    ],
  },
  {
    id: "2",
    type: "Caterers",
    vendors: [
      {
        id: "1",
        name: "Gourmet Delights",
        image: "https://source.unsplash.com/800x600/?catering",
        rating: "4.6",
        price: "$30/person",
      },
      {
        id: "2",
        name: "Tasty Bites",
        image: "https://source.unsplash.com/800x600/?food",
        rating: "4.4",
        price: "$25/person",
      },
      {
        id: "3",
        name: "Chef's Special",
        image: "https://source.unsplash.com/800x600/?chef",
        rating: "4.9",
        price: "$40/person",
      },
      {
        id: "4",
        name: "Healthy Eats",
        image: "https://source.unsplash.com/800x600/?healthy",
        rating: "4.7",
        price: "$35/person",
      },
    ],
  },
  {
    id: "3",
    type: "Decorations",
    vendors: [
      {
        id: "1",
        name: "Elegant Designs",
        image: "https://source.unsplash.com/800x600/?decoration",
        rating: "4.5",
        price: "$1000/event",
      },
      {
        id: "2",
        name: "Creative Touch",
        image: "https://source.unsplash.com/800x600/?decor",
        rating: "4.8",
        price: "$1200/event",
      },
      {
        id: "3",
        name: "Floral Magic",
        image: "https://source.unsplash.com/800x600/?flowers",
        rating: "4.6",
        price: "$900/event",
      },
      {
        id: "4",
        name: "Luxury Themes",
        image: "https://source.unsplash.com/800x600/?luxury",
        rating: "4.7",
        price: "$1500/event",
      },
    ],
  },
  {
    id: "4",
    type: "Photographer",
    vendors: [
      {
        id: "1",
        name: "Capture Moments",
        image: "https://source.unsplash.com/800x600/?photographer",
        rating: "4.7",
        price: "$300/hr",
      },
      {
        id: "2",
        name: "Lens Master",
        image: "https://source.unsplash.com/800x600/?camera",
        rating: "4.9",
        price: "$400/hr",
      },
      {
        id: "3",
        name: "Photo Artistry",
        image: "https://source.unsplash.com/800x600/?photography",
        rating: "4.8",
        price: "$350/hr",
      },
      {
        id: "4",
        name: "Shutterbug",
        image: "https://source.unsplash.com/800x600/?photo",
        rating: "4.6",
        price: "$320/hr",
      },
    ],
  },
];
